### ISSUE TITLE
Requirement for being compliant with the papiNet API Standard

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#131]
papiNet is specifying a standard for API for the forest and paper industries.
If items not defined by papiNet are sent using papiNet endpoints, then it is not a papiNet API .Standard anymore.

Should papiNet add the following property to all subschemas?
additionalProperties: false

**Comment by patricekrakow** [comment]
One of the "advantage" of JSON over XML is to be more flexible, allowing unknown/additional properties. It has opened a brand new space of backward compatibility: it might be possible continue to use an "old client" with a "new server" because the client has been programmed to take the properties it needs and to ignore the other ones. Therefore, if the "new server" makes an update of the JSON schema while keeping the "old properties" at the same place within the structure, the "old client" can still use the "new server".

This possible decoupling between the life cycle of "clients" and the "servers" when they change their interfaces (JSON Schemas) in a **backward compatible manner** can be considered as a game changer between JSON interfaceds and XML interfaces.

Using `additionalProperties: false` is precisely define annihilating of JSON over XML.

**Comment by patricekrakow** [comment]
After a vote, we decided not to add `additionalProperties: false` for now.
We might re-discuss this topic later.

**Comment by patricekrakow** [comment]
In the meantime, if we decide to be strict, we would prefer to use `unevaluatedProperties: false`.

**Comment by patricekrakow** [comment]
On the 2024-09-11 (Wed), we had a (very) long debate regarding having **STRICT** (using `unevaluatedProperties: false`) vs **NON-STRICT** (default) JSON schemas in our OpenAPI document, from 09:00 until 11:00 (2 hours).
At the end, we decided that we will start with **STRICT** JSON schemas.

**Comment by patricekrakow** [comment]
`type: object` appears **231** times!

Done, see commit [abc30e2](https://github.com/papinet/papiNet-API/commit/abc30e2ca9f9db1eb63c9eeac8c2fb6a38cb1ece).
