### ISSUE TITLE
A POST without an uuid versus with an uuid created by the client

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#162]
In version 2.0.0 there is a Post of a purchase-order without an uuid. The server creates the uuid.
In version 3.0.0 there is a Post of a logistics-delivery-note with an uuid. The client creates the uuid.

Shouldn't papiNet be consistent in specifying an POST of an item?
Please explain why it is different for a purchase-order and a logistics-delivery-note.

Please outline pros and cons for uuid created by the server and created by the client.

Will a request to the server GET logistics-delivery-notes include also the ones with uuid created by the client?

**Comment by patricekrakow** [comment]
The idea is to have:

- `POST /thingies` when the _server_ owns the _thingy_, while the creation is requested by the _client_;
- `POST /thingies/{thingyId}` when the client owns the _thingy_ and wants the _server_ to get a "copy" of it.

**Comment by patricekrakow** [comment]
We will not stick to this "wobbling" idea. We agreed that it is best to consider them as "equivalent", the difference being just who creates the UUID, the server or the client. And, we will "arbitrary" (for now) favor the creation of the UUID at server-side, in order to keep the client implementation as simple as possible, see issue #168.
