### ISSUE TITLE
Property id: in POST and PUT endpoints version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#178]
As I remember, papiNet has decided that UUID should be created by the server and not by the client.
Because of that, the property id: is optional in schema for LogisticsDeliveryNoteById: and LogisticsGoodsReceiptById:.

Existing id: in json interactions for POST /logistics-delivery-notes and POST /logistics-goods-receipts should be removed.

Property id: is required in json interactions for PUT /logistics-delivery-notes/{logisticsDeliveryNoteId} and PUT /logistics-goods-receipts/{logisticsGoodsReceiptId}.
It means, that the logistics supplier before issuing a PUT /logistics-delivery-notes/{logisticsDeliveryNoteId} and a PUT /logistics-goods-receipts/{logisticsGoodsReceiptId} needs to issue a GET /logistics-delivery-notes and a GET /logistics-goods-receipts to get the id: for the logistics-delivery-note and the id: for the logistics-goods-receipt. These interactions are missing in the md-file.

**Endpoint  GET /logistics-goods-receipts is missing in the schema and needs to be added.**

It was decided that a design rule should be added to the Style Guide stating that uuid should be created by the server side, but I can't find this rule in the Style Guide.

I think it would be good to have a comment in the schema why id: is optional in LogisticsDeliveryNoteById: and LogisticsGoodsReceiptById:.

**Comment by patricekrakow** [comment]
Ideally, we could have different schemas:
- one for POST in which `id` is not present
- one for GET and PUT in which the `id` is present and `required`

Instead of that we have a common schema in which `id` but not required.

[ ] I will explore if I can find a way to have these two schemas **without** the need of an horrible copy-paste...

We can prevent the need of a GET between a POST and a PUT by returning the `id` within the POST response. There are two different techniques to do that:
1. Returning a "full" instance;
2. Or, using the `Location` header in the response.

[ ] I will describe the second one as it would not required to add additional API endpoints.

**Comment by larsolofsson** [comment]
I think it would be good to have 2 schemas.
•	one for POST in which id is not present
•	one for GET and PUT in which the id is present and required

Solution:
A schema for GET and PUT in which the id is present and required
AllOf
    id
    A reference to the POST schema

**Comment by patricekrakow** [comment]
The usage of `allOf` seems to work, but we might need a little tweak to combine it with `unevaluatedProperties: false`. I will explain in details shortly...

**Comment by patricekrakow** [comment]
Let's validate a prototype of a design pattern with <https://json-everything.net/json-schema>.

Let's start with the following schema:
```yaml
# ThingyWithoutId:
type: object
unevaluatedProperties: false
required:
  - name
properties:
  name:
    type: string
  value:
    type: string
```
 and the following instance:
```json
{
  "name": "country",
  "value": "Sweden"
}
```
which is valid against the `ThingyWithoutId` schema.

As per design of the schema, the instance:
```json
{
  "name": "country"
}
```
is still valid against the schema, while is instance:
```json
{
  "value": "Sweden"
}
```
is not.
Because of the `unevaluatedProperties: false`, the instance:
```json
{
  "id": "96c64318-6331-40b3-89e7-ddebd7b1c60e",
  "name": "country",
  "value": "Sweden"
}
```
is not valid against the schema, as well as the instance:
```json
{
  "name": "country",
  "value": "Sweden",
  "extra": "EU"
}
```
We could now think about adding the `id` property using `allOf` as follow:
```yaml
ThingyWithoutId:
  type: object
  unevaluatedProperties: false
  required:
    - name
  properties:
    name:
      type: string
    value:
      type: string

# ThingyById
allOf:
  - $ref: '#/ThingyWithoutId'
  - type: object
    unevaluatedProperties: false
    required:
      - id
    properties:
      id:
        type: string
        format: uuid
```
in order to validate the instance:
```json
{
  "id": "96c64318-6331-40b3-89e7-ddebd7b1c60e",
  "name": "country",
  "value": "Sweden"
}
```
Unfortunately, it does not work because the instance cannot **at the same** have `name` and `value` **without anything else** (as instructed by `unevaluatedProperties: false`) **and** have `id` **without anything else** (as instructed by `unevaluatedProperties: false`)!
The validation will work if we remove **both** `unevaluatedProperties: false` as follow:
```yaml
ThingyWithoutId:
  type: object
  required:
    - name
  properties:
    name:
      type: string
    value:
      type: string

# ThingyById
allOf:
  - $ref: '#/ThingyWithoutId'
  - type: object
    required:
      - id
    properties:
      id:
        type: string
        format: uuid
```
However, that would not be OK as it would allow to have properties not defined in the schema, such as in the following instance:
```json
{
  "id": "96c64318-6331-40b3-89e7-ddebd7b1c60e",
  "name": "country",
  "value": "Sweden",
  "extra": "EU"
}
```
Fortunately, ...

**Comment by patricekrakow** [comment]
Let's discuss this design pattern during our next papiNet CWG meeting on the 2024-11-06 (Wed).

**Comment by patricekrakow** [comment]
On the 2024-08-14 (Wed), we had a long and interesting (but not finished) discussion about the difference between:

1. `POST /thingies` with `{ data }` as request payload, expecting the server-side to create a server-side UUID (to be returned);

2. `POST /thingies/{thingyId}` with `{ data }` or `{ id, data }` as request payload, expecting the server-side to accept the client-side UUID;

3. `POST /thingies` with `{ id, data }` as request payload, expecting the server-side to accept the client-side UUID.

**Comment by patricekrakow** [comment]
If we go for option 3, where the `id´ is required in the `POST` request payload, then we do not need multiple schemas!

**Comment by patricekrakow** [comment]
If we go for option 3, we just have to make:
- `LogisticsDeliveryNoteById.id` back to `required`
- `LogisticsGoodsReceiptById.id` back to `required`

> The instances are already containing the `id`.

**Comment by patricekrakow** [comment]
Done, see commit [793890d](https://github.com/papinet/papiNet-API/commit/793890d0022647ca045e9cc6414b515e3cf57050).
