### ISSUE TITLE
npm throws warnings on mock install

### ISSUE THREAD

**Issue by globaltopmedia** [papinet/papiNet-API#18]
Step 4 of instruction in /1.0.0/mock/install.md throws the following warnings

npm WARN papinet-mock@1.0.0 No repository field.
npm WARN papinet-mock@1.0.0 No license field.

**Comment by patricekrakow** [comment]
Regarding the `npm WARN papinet-mock@1.0.0 No repository field.` I would indeed go for the following:

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/papinet/papiNet-API",
    "directory": "1.0.0/mock"
  }
}
```

For the `npm WARN papinet-mock@1.0.0 No license field.` we could either use "Apache License 2.0" as for the standard, but I would go with "MIT", in order to emphasize that the mock is a non-formative part of the papiNet standard:

```json
{
  "license" : "MIT"
}
```

**Comment by patricekrakow** [comment]
Fixed by https://github.com/papinet/papiNet-API/pull/45.
