### ISSUE TITLE
Property assignedBy for otherIdentifier and sellerProductOtherIdentifier

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#53]
I would like to have a clarification about how to use property assignedBy for otherIdentifier and sellerProductOtherIdentifier.

Property assignedBy i optional with enumerations Customer and Seller. Only one occurence exists for otherIdentifier and sellerProductOtherIdentifier.
As far as I can see, the context defines if these identifiers are defined by the Seller or the Customer.
Why do we have this property assignedBy?

It would be more clear for implementers if the property assignedBy was required and always showing the owner of these identifiers. A bit confusing now when it is optional.

**Comment by patricekrakow** [comment]
I think we do have the `assignedBy` property in order to anticipate that we will have more party types in the future. Today, with only the `Seller` and `Customer` values, it is true that the `assignedBy` property is redundant with the context.
If we decide to keep the `assignedBy` property, we can make it `required`. Let's discuss this issue during our next meeting (2022-07-27).

**Comment by patricekrakow** [comment]
We keep the `assignedBy` property and we make it `required`.

**Comment by patricekrakow** [comment]
If we accept issue #66  there will be no `otherIdentifier` properties anymore :-)

**Comment by patricekrakow** [comment]
Following the issue #66, there will be no `otherIdentifier` property anymore, so we can close this issue.
