### ISSUE TITLE
CreateCustomerArticle and ListCustomerArticles

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#54]
Only property name is required in CreateCustomerArticle.
How can property productType with enum Paper be required in ListCustomerArticles when property paper in CreateCustomerArticle is optional?
What should be required in CreateCustomerArticle?

I suppose that it might be difficult for the client to select a customer article in the list of customer articles by using only the property name. I suppose that the the name can be the same for several customer articles with the same type paper but with different reel configurations, e.g. different reel widths.

I propose that the property otherIdentifier also should be required in both CreateCustomerArticle and ListCustomerArticles. I think that to select a customer article in the list of customer articles is best done by otherIdentifier.

GET /customer-articles ~ ListCustomerArticles has status and otherIdentifier as filter parameters.
Shouldn't these filter parameters also be required in CreateCustomerArticle and ListCustomerArticles?

**Comment by patricekrakow** [comment]
We cannot make the `paper` property `required` because we will have other properties for other types of "product", e.g. pulp, wood products, book manufacturing, ...

You also have to remember that we can express all constraints with a JSON schema.

I would say that `otherIdentifer` MUST NEVER be `required`, as it is just a transition tool to make the link between identifiers created in the context of APIs (which are always UUID) and identifiers created in the context of XML or paper messages.

Let's discuss this issue during our next meeting (2022-07-27).

**Comment by patricekrakow** [comment]
@Patrice will make some research to see if we can express our constraint - "we want (only) one of these properties to be in the object" - with the JSON schema.
We did not close (yet) the discussions around `otherIdentifier` as a tool to have coexistence between API and XML, but for now, it's good enough to have it optional.

**Comment by patricekrakow** [comment]
This issue might become obsolete if we adopt issue #66.

**Comment by patricekrakow** [comment]
Following the issue https://github.com/papinet/papiNet-API/issues/66, there will be no otherIdentifier property anymore, so we can close this issue.
