### ISSUE TITLE
Catalogue use case: Should we add a property specifying if the seller-product and the customer-article are fully specified?

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#69]
Catalogue use case: Should we add a property specifying, if the seller-product and the customer-article are fully specified?

**Comment by patricekrakow** [comment]
When you get the representation of a `seller-product` or `customer-article`, the presence of properties with the plural or range termination shows that it is not fully specified. When all the properties have a single value, it is fully specified.
When you get the identifier of an item that belongs to a `seller-product` or `customer-article`, the presence or the absence of the `paper` (or `pulp`, ...) property makes it clear if it is fully specified of not.

**Comment by patricekrakow** [comment]
What if the customer wants to create a customer-article without specifying all the open properties as it can accept all the values proposed by the seller. (...) `fullySpecified: true | false`. We will have to invent more scenario to play with that property within the Catalogue used case.

**Comment by patricekrakow** [comment]
The idea of this `fullySpecificied` property is to distinguished between not providing-a-specific-value-for-a-specific-property-because-I-will-specificy-it-late (`fullySpecified: false`); and not providing-a-specific-value-for-a-specific-property-because-I-let-the-seller-choose (`fullySpecified: true`). We still want to clearly differentiate between these tow cases, but we don't think `fullySpecificied` is a good property name.

We suggest `definitionState: fully-defined-by-the-customer | will-be-further-defined-by-the-customer-on-order | can-be-further-defined-by-the-seller-on-order (default)`. The property is not `required`.

**Comment by patricekrakow** [comment]
This discussion will be continued in issue #141...
